apiVersion: v1
kind: Service
metadata:
  name: devops-first-app
spec:
  selector:
    app: devops-first-app
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 31998
  type: NodePort